services:
  backend:
    build: .
    command: uvicorn backend.api:app --host 0.0.0.0 0--port 8000
    ports:
      - 8000:8000
    
  frontend:
    build: .
    command: streamlit run app.py
    ports:
      - 8501:8501